import { Teacher } from "@/lib/types";
import { createStore } from "zustand/vanilla";

export type TeacherState = {
  teachers: Teacher[];
};

export type TeacherActions = {
  addTeacher: (teacher: Teacher) => void;
  deleteTeacher: (id: number) => void;
  updateTeacher: (id: number, teacher: Teacher) => void;
  updateTeacherPhoto: (id: number, photo: string) => void;
};

export type TeacherStore = TeacherState & TeacherActions;

export const defaultInitState: TeacherState = {
  teachers: [
    {
      id: 1,
      firstName: "Kunal",
      lastName: "Varma",
      department: "Science",
      qualifications: "B.Ed.",
      salary: 50000,
      gender: "Male",
      onDutyToday: true,
      performance: "Good",
      workingSince: 2015,
      active: true,
      teacherDetails: {
        id: 1,
        city: "Hyderabad",
        contact: 823838293,
        country: "India",
        email: "kunalvarma943@gmail.com",
        experience: 5,
        pinCode: 500002,
        specialization: "Science",
        state: "Telangana",
        streetAddress: "8482, Road No. 12 Banjara Hills",
      },
    },
    {
      id: 2,
      firstName: "Anita",
      lastName: "Sharma",
      department: "Mathematics",
      salary: 52000,
      gender: "Female",
      qualifications: "M.Sc.",
      onDutyToday: false,
      performance: "Excellent",
      workingSince: 2012,
      active: true,
      teacherDetails: {
        id: 2,
        city: "Delhi",
        contact: 987654321,
        country: "India",
        email: "anitasharma12@gmail.com",
        experience: 10,
        pinCode: 110001,
        specialization: "Algebra",
        state: "Delhi",
        streetAddress: "14, Connaught Place",
      },
    },
    {
      id: 3,
      firstName: "Ramesh",
      lastName: "Iyer",
      department: "History",
      qualifications: "B.Com",
      salary: 48000,
      gender: "Male",
      onDutyToday: true,
      performance: "Average",
      workingSince: 2018,
      active: true,
      teacherDetails: {
        id: 3,
        city: "Mumbai",
        contact: 912345678,
        country: "India",
        email: "rameshiyer88@gmail.com",
        experience: 7,
        pinCode: 400001,
        specialization: "Modern History",
        state: "Maharashtra",
        streetAddress: "22, Fort Road",
      },
    },
    {
      id: 4,
      firstName: "Meera",
      lastName: "Patel",
      department: "English",
      qualifications: "B.A.",
      salary: 53000,
      gender: "Female",
      onDutyToday: true,
      performance: "Good",
      workingSince: 2010,
      active: true,
      teacherDetails: {
        id: 4,
        city: "Ahmedabad",
        contact: 998877665,
        country: "India",
        email: "meerapatel.eng@gmail.com",
        experience: 12,
        pinCode: 380015,
        specialization: "Literature",
        state: "Gujarat",
        streetAddress: "7, Satellite Road",
      },
    },
    {
      id: 5,
      firstName: "Arjun",
      lastName: "Mishra",
      department: "Physics",
      salary: 60000,
      gender: "Male",
      qualifications: "M.Sc.",
      onDutyToday: false,
      performance: "Excellent",
      workingSince: 2016,
      active: true,
      teacherDetails: {
        id: 5,
        city: "Lucknow",
        contact: 911112223,
        country: "India",
        email: "arjunm.physics@gmail.com",
        experience: 9,
        pinCode: 226001,
        specialization: "Quantum Mechanics",
        state: "Uttar Pradesh",
        streetAddress: "45, Gomti Nagar",
      },
    },
    {
      id: 6,
      firstName: "Divya",
      lastName: "Nair",
      department: "Biology",
      salary: 49000,
      gender: "Female",
      onDutyToday: true,
      qualifications: "B.Sc.",
      performance: "Good",
      workingSince: 2017,
      active: true,
      teacherDetails: {
        id: 6,
        city: "Kochi",
        contact: 902938471,
        country: "India",
        email: "divyanair.bio@gmail.com",
        experience: 6,
        pinCode: 682020,
        specialization: "Genetics",
        state: "Kerala",
        streetAddress: "99, MG Road",
      },
    },
    {
      id: 7,
      firstName: "Sahil",
      lastName: "Khan",
      department: "Chemistry",
      salary: 51000,
      gender: "Male",
      onDutyToday: false,
      performance: "Average",
      qualifications: "M.Sc.",
      workingSince: 2014,
      active: true,
      teacherDetails: {
        id: 7,
        city: "Bhopal",
        contact: 888776655,
        country: "India",
        email: "sahilkhan.chem@gmail.com",
        experience: 8,
        pinCode: 462001,
        specialization: "Organic Chemistry",
        state: "Madhya Pradesh",
        streetAddress: "17, Arera Colony",
      },
    },
    {
      id: 8,
      firstName: "Priya",
      lastName: "Menon",
      department: "Computer Science",
      salary: 62000,
      gender: "Female",
      onDutyToday: true,
      performance: "Excellent",
      workingSince: 2019,
      qualifications: "B.Tech",
      active: true,
      teacherDetails: {
        id: 8,
        city: "Chennai",
        contact: 934567890,
        country: "India",
        email: "priyamenon.cs@gmail.com",
        experience: 5,
        pinCode: 600028,
        specialization: "AI & ML",
        state: "Tamil Nadu",
        streetAddress: "210, T. Nagar",
      },
    },
    {
      id: 9,
      firstName: "Vikram",
      lastName: "Joshi",
      department: "Geography",
      qualifications: "B.Sc.",
      salary: 47000,
      gender: "Male",
      onDutyToday: false,
      performance: "Good",
      workingSince: 2011,
      active: true,
      teacherDetails: {
        id: 9,
        city: "Pune",
        contact: 901234567,
        country: "India",
        email: "vikramjoshi.geo@gmail.com",
        experience: 13,
        pinCode: 411001,
        specialization: "Earth Science",
        state: "Maharashtra",
        streetAddress: "56, FC Road",
      },
    },
    {
      id: 10,
      firstName: "Nikita",
      lastName: "Reddy",
      department: "Economics",
      salary: 55000,
      gender: "Female",
      onDutyToday: true,
      qualifications: "M.Sc.",
      performance: "Excellent",
      workingSince: 2013,
      active: true,
      teacherDetails: {
        id: 10,
        city: "Hyderabad",
        contact: 909090909,
        country: "India",
        email: "nikitareddy.eco@gmail.com",
        experience: 11,
        pinCode: 500003,
        specialization: "Microeconomics",
        state: "Telangana",
        streetAddress: "12, Jubilee Hills",
      },
    },
    {
      id: 11,
      firstName: "Raj",
      lastName: "Kapoor",
      department: "Political Science",
      salary: 52000,
      gender: "Male",
      onDutyToday: false,
      qualifications: "B.Ed.",
      performance: "Good",
      workingSince: 2016,
      active: true,
      teacherDetails: {
        id: 11,
        city: "Jaipur",
        contact: 890123456,
        country: "India",
        email: "rajkapoor.pol@gmail.com",
        experience: 8,
        pinCode: 302001,
        specialization: "Indian Politics",
        state: "Rajasthan",
        streetAddress: "33, MI Road",
      },
    },
    {
      id: 12,
      firstName: "Sneha",
      lastName: "Das",
      department: "Psychology",
      salary: 56000,
      gender: "Female",
      onDutyToday: true,
      qualifications: "M.Sc.",
      performance: "Excellent",
      workingSince: 2020,
      active: true,
      teacherDetails: {
        id: 12,
        city: "Kolkata",
        contact: 921234567,
        country: "India",
        email: "sneha.das.psy@gmail.com",
        experience: 4,
        pinCode: 700001,
        specialization: "Child Psychology",
        state: "West Bengal",
        streetAddress: "76, Park Street",
      },
    },
    {
      id: 13,
      firstName: "Aman",
      lastName: "Singh",
      department: "Philosophy",
      salary: 48000,
      gender: "Male",
      qualifications: "B.Ed.",
      onDutyToday: false,
      performance: "Average",
      workingSince: 2015,
      active: true,
      teacherDetails: {
        id: 13,
        city: "Patna",
        contact: 930456789,
        country: "India",
        email: "amansingh.phil@gmail.com",
        experience: 9,
        pinCode: 800001,
        specialization: "Ethics",
        state: "Bihar",
        streetAddress: "15, Fraser Road",
      },
    },
    {
      id: 14,
      firstName: "Neha",
      lastName: "Agarwal",
      department: "Music",
      salary: 45000,
      gender: "Female",
      onDutyToday: true,
      performance: "Good",
      workingSince: 2018,
      qualifications: "M.Sc.",
      active: true,
      teacherDetails: {
        id: 14,
        city: "Indore",
        contact: 998899889,
        country: "India",
        email: "neha.music@gmail.com",
        experience: 6,
        pinCode: 452001,
        specialization: "Classical Music",
        state: "Madhya Pradesh",
        streetAddress: "8, Rajwada Chowk",
      },
    },
    {
      id: 15,
      firstName: "Farhan",
      qualifications: "B.Ed.",
      lastName: "Ali",
      department: "Physical Education",
      salary: 46000,
      onDutyToday: false,
      performance: "Good",
      workingSince: 2014,
      active: true,
      gender: "Male",
      teacherDetails: {
        id: 15,
        city: "Nagpur",
        contact: 987123456,
        country: "India",
        email: "farhanali.pe@gmail.com",
        experience: 10,
        pinCode: 440001,
        specialization: "Fitness & Training",
        state: "Maharashtra",
        streetAddress: "65, Sitabuldi",
      },
    },
  ],
};

export const createTeacherStore = (
  initState: TeacherState = defaultInitState,
) => {
  return createStore<TeacherStore>()((set) => ({
    ...initState,
    addTeacher: (teacher: Teacher) =>
      set((state) => ({
        teachers: [...state.teachers, teacher],
      })),
    deleteTeacher: (id: number) =>
      set((state) => ({
        teachers: state.teachers.filter((teacher) => teacher.id !== id),
      })),
    updateTeacher: (id: number, teacher: Teacher) =>
      set((state) => ({
        teachers: state.teachers.map((t) => (t.id === id ? teacher : t)),
      })),
    updateTeacherPhoto: (id: number, photo: string) =>
      set((state) => ({
        teachers: state.teachers.map((t) =>
          t.id === id ? { ...t, photo } : t,
        ),
      })),
  }));
};
